### ISSUE TITLE
切换单位固定为合同中的单位

### ISSUE THREAD

**Issue by zonglu666** [steedos/records#104]
合同单位包括：
集团公司办公室
股份公司办公室
一公司
二公司
三公司
杂货公司
六公司
七公司
八公司
九公司
铁运公司
流机公司
船舶公司
劳务公司
电力公司
物流公司
外理公司
物资公司
卫环中心
安保中心
技术中心
结算中心
技术中心

**Comment by marchtian** [comment]
![image](https://user-images.githubusercontent.com/7553007/52545351-cfe88080-2df1-11e9-8cc3-c69ecd097354.png)
