### ISSUE TITLE
档号、件号自动生成

### ISSUE THREAD

**Issue by liminglang** [steedos/records#23]
- [ ]  接收之后，先选中多条记录，然后批量生成件号，根据件号去自动生成档号
- [ ] 接收时，要自动生成电子文件号：全宗号+年度+5位流水号
- [ ] 机构、保管期限发生变动时，机构代码、保管期限代码相应发生变动；
- [ ] 档号生成后，机构代码或保管期限代码或件号发生变动时，档号也随之发生变动。

**Comment by liminglang** [comment]
集团公司总部文书类档案按照“年度-保管期限-机构” 分类， 档号基本结构为“全宗号-档案门类代码-年度-保管期 限-机构代码-件号”。 例如：A001-WS-2016-Y-BGS-0001。 说明：集团公司-文书档案-2016年度-永久-办公室-件号 为1的文件。

**Comment by zonglu666** [comment]
档号编制规则：
1．集团公司总部文书类档案按照“年度-保管期限-机构” 分类， 档号基本结构为“全宗号-档案门类代码-年度-保管期 限-机构代码-件号”。 例如：A001-WS-2016-Y-BGS-0001。 说明：集团公司-文书档案-2016年度-永久-办公室-件号 为1的文件。
2．各分子公司推荐采用“年度-保管期限”分类，在档号 基本结构的基础上，省略机构代码，其档号结构为“全宗号档案门类代码-年度-保管期限-件号”。 例如：D020-WS-2016-D30-0015。 说明：港口机械公司-文书档案-2016年度-定期30年-件号 为15的文件
