### ISSUE TITLE
【一期】导入旧版档案数据的原文和附件。

### ISSUE THREAD

**Issue by zonglu666** [steedos/records#40]
1、拷贝服务器上的附件到本地
2、循环遍历上传本地的附件

**Comment by chenzhipei** [comment]
将js文件中的代码拷贝到客户端，执行测试上传前修改脚本中的路径地址
[uploadAttachments.zip](https://github.com/steedos/records/files/1957460/uploadAttachments.zip)

**Comment by zonglu666** [comment]
6月15日导入2017年集团文书档案的正文和附件

**Comment by marchtian** [comment]
遗留问题
（1）现在在前台看不到 导入过来的老档案、实际数据库里是有的，待写脚本、给某个字段赋值
（2）17年11-12月附件已导入，其余待导入

**Comment by chenzhipei** [comment]
不处理
