### ISSUE TITLE
档案借阅、移交、销毁待恢复流程

### ISSUE THREAD

**Issue by liminglang** [steedos/records#58]
档案移交、销毁的待沟通问题：
- [ ] 哪些档案可以移交？
- [ ] 档案移交到哪？移交给谁？第一步由谁审核？
- [ ] 移交之后还可以对该档案做哪些操作？
- [ ] 哪些档案可以被销毁？
- [ ] 档案销毁之后还可以对该档案做哪些操作？

**Comment by lizhenghotoa** [comment]
档案移交：以二公司（移交单位）档案移交到三公司（接收单位）为例，发生档案单位变更后会出现移交操作。
产生移交操作后， 移交单位应能够在移交界面看到移交清单（只能看到条目，不能看到条目具体的文件）、移交痕迹的记录。
移交单位如需查看移交档案需向接收单位发起借阅审批。
移交的具体流程：二公司档案管理员 （移交条目、原文）—— 二公司主管档案主任——三公司主管档案主任-—— 三公司档案管理员——结束。

**Comment by lizhenghotoa** [comment]
档案销毁：系统会根据文件的保管期限自动生成销毁清册。本单位的档案管理员会根据生成的销毁清册发起销毁审批。
销毁具体流程如下：档案员——办公室主管档案主任（包含销毁文件涉及到的单位领导会签）—— 主管领导——档案管理员——结束。
需注意： 文件销毁只是纸质文件的销毁，档案系统中应保留被销毁文件的电子档案，且档案元数据中的状态标志位显示 已销毁 即可。

**Comment by marchtian** [comment]
在去年下半年时，qhd-beta 的数据库被 替换为 qhd正式的。
而原qhd-beta上 之前已建立了 借阅、移交、销毁的流程
![image](https://user-images.githubusercontent.com/7553007/52550000-0d103b00-2e11-11e9-8bd9-98b051d2502f.png)
（上图截自  77上的 qhd-beta）
并定义了object_workflows
![image](https://user-images.githubusercontent.com/7553007/52550045-56608a80-2e11-11e9-89bb-012a633afc86.png)

在现在的 档案系统（新）里，并没有流程所以需要
（1）恢复借阅、移交、销毁的流程
（2）定义object_workflows
（3）测试、确认借阅、移交、销毁的操作过程
