### ISSUE TITLE
借阅，销毁，移交流程开发

### ISSUE THREAD

**Issue by liminglang** [steedos/records#61]
- [ ] 借阅流程：借阅本单位，借阅其他单位
- [ ] 销毁流程：待沟通（和荀姐确认流程）
- [ ] 移交流程：待沟通

**Comment by lizhenghotoa** [comment]
借阅本单位：
（1）普通文件：工作人员借阅——档案管理员审批——结束。 
（2）会议纪要等重要文件： 工作人员借阅——办公室主任审批——档案管理员审批——结束。

借阅其他单位：
（1）普通文件：借阅人员发起———— 借阅人员办公室主任审批——保管单位档案员同意——结束。
（2）会议纪要等重要文件：借阅人员发起———— 借阅人员办公室主任审批——保管单位办公室主任审批——保管单位档案员同意——结束。
