### ISSUE TITLE
归档过来的文件，发文归档的机构是：拟稿单位，收文归档的机构是：所属部门

### ISSUE THREAD

**Issue by liminglang** [steedos/records#72]

**Comment by zonglu666** [comment]
1.电子文件号取消，不在归档生成
2.归档增加全宗号字段，与全宗名称字段一起增加
3.查找保管期限ID，根据保管期限,设置处理标志

**Comment by marchtian** [comment]
收文单，无所属部门，故未见 收文单 的机构
![image](https://user-images.githubusercontent.com/7553007/52545071-a9c1e100-2def-11e9-8932-4c6bf326d703.png)
