### ISSUE TITLE
一阶段需完成的历史数据导入

### ISSUE THREAD

**Issue by marchtian** [steedos/records#85]
截止6月，已将2017年全年的 文书档案记录及正文附件 导入到了  先档案系统之中

**Comment by marchtian** [comment]
正确认 一阶段 是否就只 需2017年的数据？
如果 需其他的数据，还需确认 先服务器是否 OK

**Comment by zonglu666** [comment]
导入2017年全年数据

**Comment by chenzhipei** [comment]
导入2017年11、12月数据，修改相关接口
